
# tap repositories and their packages

tap homebrew/core
brew aom
brew autoconf
brew boost
brew cairo
brew colordiff
brew coreutils
brew diffutils
brew direnv
brew docker
brew ed
brew emacs
brew ffmpeg
brew findutils
brew flac
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew gawk
brew gcc
brew gdbm
brew gettext
brew ghostscript
brew giflib
brew git
brew glib
brew gmp
brew gnu-sed
brew gnu-tar
brew gnutls
brew gperftools
brew graphite2
brew grep
brew gzip
brew harfbuzz
brew htop
brew icu4c
brew isl
brew jpeg
brew juman
brew lame
brew leptonica
brew libass
brew libbluray
brew libevent
brew libffi
brew libidn2
brew libmpc
brew libogg
brew libomp
brew libpng
brew libsamplerate
brew libsndfile
brew libsoxr
brew libtasn1
brew libtiff
brew libunistring
brew libvorbis
brew libvpx
brew little-cms2
brew lzo
brew mas
brew mono
brew mpfr
brew ncurses
brew nettle
brew nginx
brew nkf
brew nodebrew
brew opencore-amr
brew openjpeg
brew openssl
brew opus
brew p11-kit
brew pandoc
brew pcre
brew pcre2
brew peco
brew pipenv
brew pixman
brew pkg-config
brew portaudio
brew pyenv
brew python
brew readline
brew rtmpdump
brew rubberband
brew sdl2
brew sl
brew snappy
brew source-highlight
brew speex
brew sqlite
brew sshfs
brew swiftlint
brew tesseract
brew theora
brew tinycdb
brew unbound
brew webp
brew wget
brew x264
brew x265
brew xvid
brew xz
brew zlib
brew zsh
brew zsh-autosuggestions
brew zsh-history-substring-search
brew zsh-syntax-highlighting

tap homebrew/cask
cask docker
cask mactex

tap argon/mas

tap rcmdnk/file
brew brew-file

tap uetchy/nlp
brew knp

# Other Cask applications
cask google-cloud-sdk
cask osxfuse
cask realm-browser

# App Store applications
appstore 417375580 BetterSnapTool (1.9)
appstore 1044549675 Elmedia Video Player (7.4)
appstore 406056744 Evernote (7.12)
appstore 409183694 Keynote (9.1)
appstore 405399194 Kindle (1.26.1)
appstore 961975824 Leawo Blu-ray Player (1.9.0)
appstore 539883307 LINE (5.18.3)
appstore 1349670778 Mathpix Snipping Tool (2.0)
appstore 462058435 Microsoft Excel (16.27)
appstore 462062816 Microsoft PowerPoint (16.27)
appstore 462054704 Microsoft Word (16.27)
appstore 409203825 Numbers (6.1)
appstore 823766827 OneDrive (19.123.0624)
appstore 409201541 Pages (8.1)
appstore 803453959 Slack (4.0.1)
appstore 497799835 Xcode (10.3)
