repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      # - id: shellcheck
      #   files: ^(bin|init)/
      #   types: [shell]
      - id: shfmt
        args: [-i, "2", -ci, -sr, -s]
        files: ^(bin|init)/
        types: [shell]
      - id: markdownlint
        args: [--rules, ~MD013]
