# TAP
tap "homebrew/cask-fonts"

# GNU utilities
brew "binutils"   # ld, ar, ...
brew "coreutils"  # ls, cp, rm, ...
brew "diffutils"  # diff, cmp, ...
brew "ed"
brew "findutils"  # find, locate, updatedb, xargs
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "grep"
brew "less"

# Misc
brew "ghq"     # Remote repository management made easy
brew "mackup"  # Keep your Mac's application settings in sync
brew "nkf"     # Network Kanji code conversion Filter (NKF)

# CASK
cask_args appdir: "/Applications"
cask "bettertouchtool"
cask "docker"
cask "dropbox"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "karabiner-elements"
cask "macfuse"
cask "pycharm"
cask "visual-studio-code"
cask "xquartz"

# MAS
# mas "Slack", id: 803453959  # seems to require being signed in
# mas "LINE", id: 539883307  # seems to require being signed in
# mas "Kindle", id: 405399194  # seems to require being signed in
# mas "Pages", id: 409201541
# mas "Keynote", id: 409183694
# mas "Numbers", id: 409203825
# mas "OneDrive", id: 823766827
mas "The Unarchiver", id: 425424353
