# Basic CLI tools
brew "gcc"
brew "wget"
brew "curl"
brew "cmake"
brew "meson"

# Shells
brew "zsh"

# Editors
brew "emacs"
brew "vim"

# Programming languages
brew "python"
brew "python@3.10"
brew "python@3.9"
brew "perl"
brew "ruby", args: ["force-bottle"]
brew "go"
brew "node"
brew "node@16"
# Rust is installed via rustup

# Modern alternatives to Liunx CLI tools
brew "git"        # git
brew "openssh"    # ssh
brew "tmux"       # tmux
brew "htop"       # top
brew "lsd"        # ls
brew "fd"         # find
brew "ripgrep"    # grep -r
brew "procs"      # ps
brew "colordiff"  # diff
brew "sd"         # sed/awk
brew "rargs"      # Util like xargs + awk with pattern matching support
brew "bat"        # cat
brew "git-delta"  # diff
brew "duf"        # df

# Misc
brew "moreutils"  # chronic, combine, ifne, sponge, ...
brew "tree"       # Display directories as trees (with optional color/HTML output)
brew "pipx"       # Execute binaries from Python packages in isolated environments
brew "atuin"      # Improved shell history for zsh and bash
brew "zoxide"     # Shell extension to navigate your filesystem faster
brew "peco"       # Simplistic interactive filtering tool
brew "fzf"        # Command-line fuzzy finder written in Go
brew "direnv"     # Load/unload environment variables based on $PWD
brew "watch"      # Executes a program periodically, showing output fullscreen

# System
brew "ansible"    # Automate deployment, configuration, and upgrading
brew "whois"      # Lookup tool for domain names and other internet resources
