name: lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y pre-commit shellcheck
      - name: Run pre-commit
        run: pre-commit run --all-files
