name: test-installer

on:
  schedule:
    - cron: '0 15 1 * *'  # run at 0:00 on 2nd every month (JST)
  workflow_dispatch:

jobs:
  test-installer:
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Remove pre-installed Homebrew on Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#homebrew-note
        run: sudo rm -rf /home/linuxbrew/
      - name: Run installer
        run: SUDO=1 sh -c "$(curl -fsSL https://raw.githubusercontent.com/nobu-g/dotfiles/main/install.sh)"
      - name: Test environment
        run: cd $HOME/dotfiles && make test
