name: test-installer

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Run installer
        run: SUDO=1 sh -c "$(curl -fsSL https://raw.githubusercontent.com/nobu-g/dotfiles/main/install.sh)"
      - name: Test environment
        run: cd $HOME/dotfiles && make test
