name: test-installer

on:
  schedule:
    - cron: '0 15 1 * *'  # run at 0:00 on 2nd every month (JST)
  workflow_dispatch:

jobs:
  test-installer:
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]  # Juman++ cannot be built on ubuntu:22.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run installer
        run: SUDO=1 sh -c "$(curl -fsSL https://raw.githubusercontent.com/nobu-g/dotfiles/main/install.sh)"
      - name: Test environment
        run: cd $HOME/dotfiles && make test
