name: test-macos

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-macos:
    runs-on: macos-latest
    timeout-minutes: 120
    steps:
    - name: Remove pre-installed Homebrew
      run: |
        sudo rm -rf /usr/local/Homebrew
        sudo rm -rf /usr/local/Caskroom
        sudo rm -f /usr/local/bin/brew
        sudo rm -rf /opt/homebrew
    - name: Remove pre-installed Apps
      run: |
        sudo rm -rf '/Applications/Google Chrome.app'
    - name: Check out code
      uses: actions/checkout@v6
      with:
        path: dotfiles
    - name: Install dotfiles
      run: make install
      working-directory: ./dotfiles
    - name: Test commands
      run: make test
      working-directory: ./dotfiles
