name: test-macos

on: [push]

jobs:
  macos:
    runs-on: macos-latest
    steps:
    # - uses: actions/checkout@v2
    - name: debug print pwd
      run: pwd; env
    - name: Clone this repo
      run: git clone --depth 1 https://github.com/nobu-g/dotfiles.git
    - name: Install dotfiles
      run: make install
      working-directory: ./dotfiles
    - name: Test commands
      run: make test
      working-directory: ./dotfiles
