name: test-installer

on:
  schedule:
    - cron: '0 15 1 * *'  # run at 0:00 on 2nd every month (JST)
  workflow_dispatch:

jobs:
  test-installer:
    runs-on: ubuntu-latest
    steps:
      - name: Run installer
        run: SUDO=1 sh -c "$(curl -fsSL https://raw.githubusercontent.com/nobu-g/dotfiles/main/install.sh)"
      - name: Test environment
        run: cd $HOME/dotfiles && make test
